import type { Metadata } from "next";
import "./globals.css";
import { NavProvider } from "@/context/NavContext";
import { Inter } from "next/font/google";
import NavigationMenu from "./components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} antialiased`}>
        <NavProvider>
          <NavigationMenu></NavigationMenu>
          {children}
        </NavProvider>
      </body>
    </html>
  );
}
